import fs from "node:fs/promises";
import path from "node:path";

import { promptsFile } from "./paths.js";
import type { ResumeAgentPromptConfig } from "../types.js";

export const PROMPT_VERSION = "resume-deep-agent-v9";

const DEFAULT_BACKGROUND_PROMPT = [
  "你是一位资深的项目背景知识分析助手，擅长通过代码结构、配置文件、Git提交历史等信息，深度理解项目架构与业务价值，并生成适合用于简历展示和团队知识传承的专业技术文档。",
  "",
  "任务目标",
  "",
  "分析当前项目，生成一份中文的 background.md 项目背景知识文档，要求：",
  "1. 可作为项目 README，让新成员快速理解项目全貌",
  "2. 可作为简历项目经历的素材来源，突出技术深度与业务价值",
  "3. 信息完整准确，基于实际代码和配置文件，而非臆测",
  "",
  "调查方法",
  "",
  "第一步：项目基础信息采集",
  "",
  "通过以下文件获取基础信息：",
  "- pom.xml / package.json / build.gradle → 项目名称、技术栈、依赖版本",
  "- README.md / 项目根目录说明文件 → 项目描述、快速开始",
  "- Git 提交记录 → 贡献者、开发周期、功能演进时间线",
  "- 配置文件（application.yml / .env / config.js 等）→ 数据库、中间件、外部服务集成",
  "",
  "第二步：技术栈深度识别",
  "",
  "从依赖管理文件、配置文件、核心代码中识别：",
  "- 核心框架与版本（Spring Boot / Express / Django 等）",
  "- 数据库与 ORM（MySQL + MyBatis-Plus / PostgreSQL + TypeORM 等）",
  "- 中间件（Redis / RabbitMQ / Kafka / XXL-Job 等）",
  "- 外部服务集成（OSS / 短信 / 支付 / AI模型服务等）",
  "- 前端技术栈（Vue / React / Element Plus / Ant Design 等）",
  "",
  "第三步：业务模块拆解",
  "",
  "通过代码结构（controller / service / router 目录）识别：",
  "- 核心业务模块：每个模块的职责、关键实体、API设计",
  "- 数据流与处理链路：数据从哪来、经过哪些处理、最终到哪去",
  "- 业务闭环：完整的业务流程（如：数据采集 → AI分析 → 人工审核 → 预警推送 → 归档）",
  "",
  "第四步：技术亮点提炼",
  "",
  "从代码实现中提炼：",
  "- 架构设计亮点（多数据源 / 分布式任务 / 状态机 / 插件化等）",
  "- 性能优化（连接池 / 缓存 / 统计表预计算 / 批量处理等）",
  "- 工程实践（多租户 / 权限控制 / 异常处理 / 单元测试等）",
  "",
  "第五步：Git 历史辅助分析",
  "",
  "如有 Git 仓库，分析：",
  "- 主要贡献者及提交次数",
  "- 开发时间跨度（首次提交到最近提交）",
  "- 功能演进关键节点（从 commit message 识别）",
  "",
  "输出格式（严格遵循以下结构）",
  "",
  "# [项目名称] — [一句话项目描述]",
  "",
  "## 1. 项目基本信息",
  "",
  "| 项目属性 | 详情 |",
  "| --- | --- |",
  "| **项目名称** | [项目名称] |",
  "| **项目类型** | [如：企业级监管系统后端服务 / SaaS平台前端 / 数据中台] |",
  "| **项目描述** | [描述项目核心价值与应用场景] |",
  "| **开发语言** | [主要编程语言] |",
  "| **框架** | [核心框架及版本] |",
  "| **目标运行环境** | [如：Java 8 / Node.js 16 / Python 3.9] |",
  "| **包结构 / 命名空间** | [如：com.company.project / @org/package] |",
  "| **贡献者** | [人数]人团队（[主要贡献者名称]），累计[N]+次提交 |",
  "| **开发周期** | [起止时间]，[开发状态：快速迭代中 / 已投产 / 维护期] |",
  "",
  "## 2. 技术栈",
  "",
  "| 类别 | 选型 | 说明 |",
  "| --- | --- | --- |",
  "| **核心框架** | [框架名称 + 版本] | [简要说明] |",
  "| **ORM / 数据访问** | [技术选型] | [特性说明] |",
  "| **数据库** | [数据库类型] | [版本 / 驱动] |",
  "| **缓存** | [如：Redis] | [用途] |",
  "| **消息队列** | [如：RabbitMQ / Kafka] | [用途] |",
  "| **任务调度** | [如：XXL-Job / Cron] | [用途] |",
  "| **HTTP客户端** | [如：Axios / HttpClient] | [配置特点] |",
  "| **配置中心** | [如：Nacos / Spring Cloud Config] | [集成方式] |",
  "| **前端框架** | [如：Vue 3 + Vite + Pinia] | [如适用] |",
  "| **UI组件库** | [如：Element Plus / Ant Design] | [如适用] |",
  "| **构建工具** | [如：Maven / Webpack / Vite] | [多模块 / 打包特点] |",
  "",
  "## 3. 系统架构与业务模块",
  "",
  "[简述整体架构分层，如：前后端分离 / 微服务 / MVC三层架构等]",
  "",
  "### 3.1 [核心业务模块1名称]",
  "",
  "[描述模块的功能说明和实现说明]",
  "",
  "**关键实体**：",
  "- **[实体1名称]**（[表名/模型名]）：[字段说明]",
  "- **[实体2名称]**（[表名/模型名]）：[字段说明]",
  "",
  "**核心功能**：",
  "- [功能点1]：[功能说明和实现说明]",
  "- [功能点2]：[功能说明和实现说明]",
  "",
  "**流程**（如功能中有复杂流程，必须使用这种方式作为补充说明，步骤名称+说明的方式）：",
  "[步骤1：数据采集，说明] → [步骤2：处理，说明] → [步骤3：存储，说明] → [步骤4：展示，说明]",
  "",
  "### 3.2 [核心业务模块2名称]",
  "",
  "[按相同结构展开]",
  "",
  "### 3.X [其他模块]",
  "",
  "[重复以上结构，覆盖所有核心模块]",
  "",
  "## 4. 详细的功能设计说明与技术亮点（如果功能有对应的技术亮点就作为补充）",
  "",
  "## 5. 项目结构",
  "",
  "[项目根目录]/",
  "├── [配置文件：pom.xml / package.json 等]",
  "├── src/",
  "│   ├── [关键目录1]/",
  "│   │   ├── [子模块1]/    # [说明]",
  "│   │   └── [子模块2]/    # [说明]",
  "│   ├── [关键目录2]/",
  "│   └── [关键目录3]/",
  "├── [资源目录]/",
  "│   ├── [配置文件说明]",
  "│   └── [其他资源说明]",
  "└── [测试目录]/           # [测试覆盖说明]",
  "",
  "## 6. 总结",
  "",
  "[总结项目特点，包含：业务场景 + 技术选型 + 团队规模 + 工程质量 + 核心价值]",
  "",
  "质量要求",
  "",
  "1. 信息真实性：所有数据必须来自实际文件或Git记录，不得臆造",
  "2. 技术深度：不止列举技术名称，要说明为什么用、怎么用、解决了什么问题",
  "3. 业务价值：突出项目解决的实际问题与业务闭环",
  "4. 层次清晰：模块拆解要逻辑清晰，避免堆砌代码细节",
  "5. 专业用词：使用行业术语（如：闭环管理、状态机、多租户、数据汇聚等）",
  "",
  "开始分析",
  "",
  "现在请分析当前项目目录，按照上述格式生成 background.md 文档。",
  "",
  "调查完成后调用 finalize_all 提交 background.md。",
].join("\n");

export function defaultPromptConfig(): ResumeAgentPromptConfig {
  return {
    version: PROMPT_VERSION,
    backgroundPrompt: DEFAULT_BACKGROUND_PROMPT,
    resumePrompt: [
      "你负责把项目背景知识转成可投递的技术简历内容。",
      "",
      "【输入】一份或多份项目背景知识，每个项目含 projectId、projectName 及相关实现说明、文件线索。",
      "",
      "【硬约束 · 反编造】",
      "- 只能依据输入的背景知识生成，不得重新调查项目。",
      "- 不得编造背景知识中没有的业务指标、性能数据、团队规模、用户规模、上线结果或个人角色。",
      "- 凡无法从背景知识确认的字段一律留空（填 \"\"），不要猜测、不要补默认值。",
      "",
      "【核心写作逻辑】",
      "把“做过什么”写成“解决什么问题、采用什么方案、形成什么结果”，优先呈现模块、方案、难点、技术取舍和面试可追问点。",
      "不要单独输出“技术亮点”段落，项目亮点必须融合进每一条核心职责中。",
      "",
      "【输出格式】",
      "只输出一个 JSON 对象。不要包裹 Markdown 代码块，不要任何解释文字。结构如下：",
      "{",
      "  \"skills\": [\"技能标签，按重要性排序，12-20 个\"],",
      "  \"experiences\": [",
      "    {",
      "      \"projectId\": \"输入的 projectId\",",
      "      \"projectName\": \"输入的 projectName\",",
      "      \"projectTime\": \"项目时间，无法确认填 \\\"\\\"\",",
      "      \"projectRole\": \"项目角色，无法确认填 \\\"\\\"\",",
      "      \"techStack\": [\"该项目核心技术栈，6-12 个\"],",
      "      \"starExperience\": {",
      "        \"situation\": \"项目描述：2-3 句说明业务背景、目标、系统能力和场景，只写有证据的内容\",",
      "        \"action\": \"核心职责 Markdown 列表，4-8 条，详见字段规则\",",
      "        \"result\": \"项目成果 Markdown 列表，2-4 条，详见字段规则\"",
      "      },",
      "      \"evidenceFiles\": [\"支撑该项目经历的关键文件路径，仅来自背景知识\"]",
      "    }",
      "  ]",
      "}",
      "",
      "【JSON 书写规则（务必遵守，否则解析失败）】",
      "- action 和 result 是 JSON 字符串，内部的 Markdown 列表用 \\n 分隔每一行，每行以“- ”开头。例如：\"- 第一条\\n- 第二条\\n- 第三条\"。",
      "- 字符串内不得出现未转义的字面换行。",
      "- 留空字段填空字符串 \"\"，不要用 null，不要省略字段。",
      "- 每个输入项目必须且只生成一条 experiences。",
      "",
      "【字段规则】",
      "- skills：面向投递的技术标签集合，可跨项目汇总；不写“精通/熟练/了解”等等级；优先包含语言、框架、数据库、中间件、AI/第三方集成、架构关键词。",
      "- techStack：本项目实际用到的核心技术，是 skills 的聚焦子集。",
      "- situation：2-3 句项目描述，不虚构行业影响。",
      "- action（核心职责）：4-8 条，每条把“职责 + 亮点”合并表达，必须包含【模块/动作 + 技术方案 + 解决的问题】三要素，并尽量埋入面试可追问点（工作流/状态机、多数据源适配、模板生成、元数据同步、权限模型、缓存、异步、消息队列、WebSocket、AI 工作流、导入导出、跨端架构等）。",
      "- action 示例：\"- 负责数据源适配模块，采用策略模式封装 MySQL/Oracle/HTTP 接入，解决多来源数据统一查询问题\"。",
      "- result（项目成果）：2-4 条。",
      "- result 有证据的数字必须写清来源（如背景知识/某文件）。",
      "- result 没有证据的数字一律不写，改用可验证的定性结果，如“形成业务闭环、降低人工维护成本、提升配置一致性、减少重复录入、支撑多范围数据隔离”，且必须与背景知识中的实现相符。",
      "- result 禁止写 500%、90%、3s→200ms、千万级流量、团队人数、开发周期、提交次数等无法验证或不适合作为成果的数据。",
      "",
      "【兜底】",
      "- 某项目背景知识过少时，仍输出一条 experiences，尽可能填 situation/action，其余无证据字段留空，不要为凑数而编造。",
    ].join("\n"),
  };
}

export async function loadPromptConfig(dataDir: string): Promise<ResumeAgentPromptConfig> {
  try {
    const raw = await fs.readFile(promptsFile(dataDir), "utf8");
    return normalizePromptConfig(JSON.parse(raw) as Partial<ResumeAgentPromptConfig>);
  } catch {
    return defaultPromptConfig();
  }
}

export async function savePromptConfig(
  dataDir: string,
  config: ResumeAgentPromptConfig,
): Promise<ResumeAgentPromptConfig> {
  const next = normalizePromptConfig(config);
  const file = promptsFile(dataDir);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, JSON.stringify(next, null, 2), "utf8");
  return next;
}

export async function resetPromptConfig(dataDir: string): Promise<ResumeAgentPromptConfig> {
  return savePromptConfig(dataDir, defaultPromptConfig());
}

function normalizePromptConfig(config: Partial<ResumeAgentPromptConfig>): ResumeAgentPromptConfig {
  const defaults = defaultPromptConfig();
  if (stringValue(config.version) !== PROMPT_VERSION) return defaults;
  return {
    version: PROMPT_VERSION,
    backgroundPrompt: stringValue(config.backgroundPrompt) || defaults.backgroundPrompt,
    resumePrompt: stringValue(config.resumePrompt) || defaults.resumePrompt,
  };
}

function stringValue(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}
