// Tauri invoke 命令注册中心。
// 单独抽出是为了让 lib.rs 不被 200+ 行的命令列表撑大；这里按模块分组，方便查找 / 增删。
// 通过 tauri-specta 注册：调试构建时会把命令签名导出为 src/bindings.ts，供前端类型安全调用。

use crate::commands::{
    api_chat, chat, chat_bridge, extras, git, project, resume, settings, stats, storage_admin,
    system, toolbox, tools, workflows,
};
use crate::{keyboard_hook, mcp_gateway};
use tauri_specta::{collect_commands, Builder};

pub fn make_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        // Git
        git::scan_directory,
        git::get_git_status,
        git::get_commit_history,
        git::get_commit_detail,
        git::get_commit_files,
        git::search_commits,
        git::get_branches,
        git::get_remotes,
        git::add_remote,
        git::verify_remote_url,
        git::remove_remote,
        git::git_push,
        git::git_pull,
        git::git_fetch,
        git::git_clone,
        git::cancel_git_clone,
        git::sync_to_remote,
        git::checkout_branch,
        git::create_branch,
        git::git_add,
        git::git_unstage,
        git::git_discard_files,
        git::git_stash_push,
        git::git_stash_pop,
        git::git_stash_apply,
        git::git_revert_commit,
        git::git_cherry_pick,
        git::get_conflict_file_content,
        git::git_checkout_conflict_version,
        git::git_mark_resolved,
        git::git_commit,
        git::git_add_and_commit,
        git::is_git_repo,
        git::git_init,
        // Project
        project::get_projects,
        project::create_project,
        project::update_project,
        project::delete_project,
        project::delete_project_directory,
        project::toggle_favorite,
        project::update_last_opened,
        project::batch_update_projects,
        project::batch_delete_projects,
        project::import_projects,
        project::reload_projects,
        project::set_project_editor,
        project::set_project_claude_env,
        // Stats
        stats::get_dashboard_stats,
        stats::refresh_dashboard_stats,
        stats::refresh_dirty_stats,
        stats::init_stats_cache,
        stats::mark_project_dirty,
        stats::mark_all_projects_dirty,
        stats::has_dirty_stats,
        stats::cleanup_stats_cache,
        // System
        system::open_in_explorer,
        system::open_in_editor,
        system::open_in_terminal,
        system::open_url,
        system::read_readme,
        system::test_terminal,
        system::check_git_version,
        system::check_node_version,
        system::get_app_paths,
        system::clear_logs,
        system::get_cursor_position,
        system::get_arch_status,
        // Toolbox - Scanner
        toolbox::scanner::scan_ports,
        toolbox::scanner::stop_scan,
        toolbox::scanner::get_common_ports,
        toolbox::scanner::check_port,
        toolbox::scanner::scan_local_dev_ports,
        // Toolbox - Downloader
        toolbox::downloader::start_download,
        toolbox::downloader::pause_download,
        toolbox::downloader::resume_download,
        toolbox::downloader::cancel_download,
        toolbox::downloader::get_download_tasks,
        toolbox::downloader::get_download_task,
        toolbox::downloader::clear_completed_downloads,
        toolbox::downloader::open_download_folder,
        toolbox::downloader::remove_download_task,
        // Toolbox - Process
        toolbox::process::get_processes,
        toolbox::process::get_port_processes,
        toolbox::process::kill_process,
        toolbox::process::get_system_stats,
        toolbox::process::get_local_port_occupation,
        // Toolbox - Forwarder
        toolbox::forwarder::add_forward_rule,
        toolbox::forwarder::remove_forward_rule,
        toolbox::forwarder::start_forwarding,
        toolbox::forwarder::stop_forwarding,
        toolbox::forwarder::get_forward_rules,
        toolbox::forwarder::get_forward_rule,
        toolbox::forwarder::get_forward_stats,
        toolbox::forwarder::update_forward_rule,
        // Toolbox - SSH Tunnel
        toolbox::ssh_tunnel::add_ssh_tunnel,
        toolbox::ssh_tunnel::update_ssh_tunnel,
        toolbox::ssh_tunnel::remove_ssh_tunnel,
        toolbox::ssh_tunnel::start_ssh_tunnel,
        toolbox::ssh_tunnel::stop_ssh_tunnel,
        toolbox::ssh_tunnel::get_ssh_tunnels,
        toolbox::ssh_tunnel::get_ssh_tunnel,
        toolbox::ssh_tunnel::get_ssh_tunnel_stats,
        toolbox::ssh_tunnel::list_ssh_config_hosts,
        toolbox::ssh_tunnel::test_ssh_tunnel,
        toolbox::ssh_tunnel::test_local_port,
        // Toolbox - Server
        toolbox::server::create_server,
        toolbox::server::start_server,
        toolbox::server::stop_server,
        toolbox::server::remove_server,
        toolbox::server::get_servers,
        toolbox::server::get_server,
        toolbox::server::update_server,
        toolbox::server::generate_nginx_config,
        // Toolbox - Docker
        toolbox::docker::docker_check_available,
        toolbox::docker::docker_find_dockerfiles,
        toolbox::docker::docker_read_dockerfile,
        toolbox::docker::docker_write_dockerfile,
        toolbox::docker::docker_generate_dockerfile_template,
        toolbox::docker::docker_generate_dockerfile_ai,
        toolbox::docker::docker_build_image,
        toolbox::docker::docker_list_images,
        toolbox::docker::docker_remove_image,
        toolbox::docker::docker_run_image,
        toolbox::docker::docker_list_containers,
        toolbox::docker::docker_inspect_container_yaml,
        toolbox::docker::docker_stop_container,
        toolbox::docker::docker_start_container,
        toolbox::docker::docker_restart_container,
        toolbox::docker::docker_remove_container,
        toolbox::docker::docker_push_image,
        // Toolbox - Claude Code
        toolbox::claude_code::check_all_claude_installations,
        toolbox::claude_code::check_claude_by_path,
        toolbox::claude_code::read_claude_config_file,
        toolbox::claude_code::write_claude_config_file,
        toolbox::claude_code::open_claude_config_dir,
        toolbox::claude_code::get_quick_config_options,
        toolbox::claude_code::apply_quick_config,
        toolbox::claude_code::get_config_profiles,
        toolbox::claude_code::save_config_profile,
        toolbox::claude_code::delete_config_profile,
        toolbox::claude_code::apply_config_profile,
        toolbox::claude_code::create_profile_from_current,
        toolbox::claude_code::scan_claude_config_dir,
        toolbox::claude_code::get_wsl_config_dir,
        toolbox::claude_code::get_saved_quick_configs,
        toolbox::claude_code::save_quick_configs,
        toolbox::claude_code::get_claude_installations_cache,
        toolbox::claude_code::save_claude_installations_cache,
        toolbox::claude_code::clear_claude_installations_cache,
        toolbox::claude_code::launch_claude_in_terminal,
        toolbox::claude_code::get_claude_launch_dirs,
        toolbox::claude_code::save_claude_launch_dirs,
        // Toolbox - Netcat
        toolbox::netcat::netcat_init,
        toolbox::netcat::netcat_create_session,
        toolbox::netcat::netcat_start_session,
        toolbox::netcat::netcat_stop_session,
        toolbox::netcat::netcat_remove_session,
        toolbox::netcat::netcat_send_message,
        toolbox::netcat::netcat_get_sessions,
        toolbox::netcat::netcat_get_session,
        toolbox::netcat::netcat_get_messages,
        toolbox::netcat::netcat_get_clients,
        toolbox::netcat::netcat_clear_messages,
        toolbox::netcat::netcat_disconnect_client,
        toolbox::netcat::netcat_update_auto_send,
        toolbox::netcat::netcat_fetch_http,
        // Toolbox - Shortcuts
        toolbox::shortcuts::get_shortcuts,
        toolbox::shortcuts::save_shortcuts,
        toolbox::shortcuts::add_shortcut,
        toolbox::shortcuts::update_shortcut,
        toolbox::shortcuts::delete_shortcut,
        toolbox::shortcuts::reset_shortcuts,
        toolbox::shortcuts::get_current_platform,
        // Toolbox - Clipboard
        toolbox::clipboard::get_clipboard_history,
        toolbox::clipboard::add_clipboard_entry,
        toolbox::clipboard::delete_clipboard_entry,
        toolbox::clipboard::toggle_pin_clipboard_entry,
        toolbox::clipboard::clear_clipboard_history,
        toolbox::clipboard::get_clipboard_settings,
        toolbox::clipboard::save_clipboard_settings,
        toolbox::clipboard::write_to_clipboard,
        toolbox::clipboard::update_clipboard_note,
        // Chat
        chat::get_chat_history_dir,
        chat::migrate_chat_history_dir,
        chat::list_chat_sessions,
        chat::get_chat_session,
        chat::create_chat_session,
        chat::save_chat_session,
        chat::rename_chat_session,
        chat::delete_chat_session,
        chat::save_compaction,
        chat::list_compactions,
        chat::get_compaction,
        chat::chat_stream,
        chat::chat_complete,
        chat::chat_cancel,
        // ApiChat
        api_chat::list_api_groups,
        api_chat::save_api_group,
        api_chat::delete_api_group,
        api_chat::list_api_endpoints,
        api_chat::save_api_endpoint,
        api_chat::delete_api_endpoint,
        api_chat::list_api_chat_sessions,
        api_chat::get_api_chat_session,
        api_chat::create_api_chat_session,
        api_chat::save_api_chat_session,
        api_chat::rename_api_chat_session,
        api_chat::delete_api_chat_session,
        api_chat::build_api_tools,
        api_chat::execute_api_endpoint,
        api_chat::fetch_api_document_url,
        // Storage admin
        storage_admin::list_data_backups,
        storage_admin::restore_from_backup,
        // MCP gateway
        mcp_gateway::mcp_gateway_status,
        mcp_gateway::mcp_gateway_internal_endpoint,
        // Tools / Tasks
        tools::chat_list_tools,
        tools::chat_execute_tool,
        tools::tasks::list_chat_tasks,
        tools::tasks::create_chat_task,
        tools::tasks::update_chat_task,
        tools::tasks::delete_chat_task,
        // Memory / Skills / Mention
        extras::get_global_memory,
        extras::save_global_memory,
        extras::list_skills,
        extras::save_skill,
        extras::delete_skill,
        extras::list_dir_entries,
        extras::read_mention_file,
        // Workflows
        workflows::workflow_list,
        workflows::workflow_get,
        workflows::workflow_save,
        workflows::workflow_delete,
        workflows::workflow_run_now,
        workflows::workflow_set_enabled,
        // Chat bridge
        chat_bridge::chat_bridge_test,
        // Settings
        settings::get_labels,
        settings::save_labels,
        settings::add_label,
        settings::remove_label,
        settings::get_categories,
        settings::save_categories,
        settings::add_category,
        settings::remove_category,
        settings::get_editors,
        settings::add_editor,
        settings::update_editor,
        settings::remove_editor,
        settings::set_default_editor,
        settings::get_terminal_config,
        settings::save_terminal_config,
        settings::get_app_settings,
        settings::save_app_settings,
        settings::get_ui_state,
        settings::save_ui_state,
        settings::get_notifications,
        settings::save_notifications,
        settings::add_notification,
        settings::remove_notification,
        settings::clear_notifications,
        settings::get_app_shortcuts,
        settings::save_app_shortcuts,
        settings::get_recommended_template,
        settings::save_recommended_template,
        settings::reset_recommended_template,
        settings::get_ai_providers,
        settings::save_ai_providers,
        settings::get_sensitive_file_patterns,
        settings::save_sensitive_file_patterns,
        // Resume
        resume::get_resumes,
        resume::save_resumes,
        resume::save_resume_knowledge,
        resume::load_resume_knowledge,
        resume::list_resume_knowledge,
        resume::list_resume_knowledge_history,
        resume::read_resume_knowledge_history,
        resume::delete_resume_knowledge,
        resume::llm_proxy_request,
        resume::resume_project_index,
        resume::resume_project_list_dir,
        resume::resume_project_read_file,
        resume::resume_project_grep,
        // Keyboard hook
        keyboard_hook::register_global_shortcuts,
        keyboard_hook::unregister_all_global_shortcuts,
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 把命令签名导出到 src/bindings.ts。
    /// 用法：`cargo test --manifest-path src-tauri/Cargo.toml export_bindings -- --nocapture`
    /// 后端改命令签名后，跑一下这个测试就能刷新前端类型。
    #[test]
    fn export_bindings() {
        use specta_typescript::{BigIntExportBehavior, Typescript};

        // u64/usize 这种 JS Number 装不下的整数：默认 spec 会报错，
        // 我们的字段（messageCount、tail_kept 之类）都在安全范围内，所以走 Number。
        make_builder()
            .export(
                Typescript::default().bigint(BigIntExportBehavior::Number),
                "../src/bindings.ts",
            )
            .expect("failed to export typescript bindings");
    }
}
