// 生成等价 nginx 配置

use crate::error::AppResult;
use super::super::{NginxConfigOptions, ProxyConfig};
use super::{ensure_servers_loaded, SERVERS};

fn escape_nginx_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn nginx_location_path(prefix: &str) -> String {
    if prefix == "/" || prefix.trim().is_empty() {
        "/".to_string()
    } else {
        format!("/{}/", prefix.trim_matches('/'))
    }
}

fn nginx_index_fallback(prefix: &str, index_page: Option<&str>) -> String {
    match index_page.map(str::trim).filter(|s| !s.is_empty()) {
        Some(page) => {
            let page = page.trim_start_matches('/');
            if prefix == "/" || prefix.trim().is_empty() {
                format!("/{}", page)
            } else {
                format!("/{}/{}", prefix.trim_matches('/'), page)
            }
        }
        None => "=404".to_string(),
    }
}

fn nginx_proxy_target(target: &str) -> String {
    let trimmed = target.trim().trim_end_matches('/');
    format!("{}/", trimmed)
}

fn push_nginx_line(out: &mut String, indent: usize, line: &str) {
    out.push_str(&" ".repeat(indent));
    out.push_str(line);
    out.push('\n');
}

fn push_cors_headers(out: &mut String, indent: &str) {
    out.push_str(&format!("{indent}add_header Access-Control-Allow-Origin * always;\n"));
    out.push_str(&format!(
        "{indent}add_header Access-Control-Allow-Methods \"GET, POST, PUT, PATCH, DELETE, OPTIONS\" always;\n"
    ));
    out.push_str(&format!(
        "{indent}add_header Access-Control-Allow-Headers \"Origin, X-Requested-With, Content-Type, Accept, Authorization\" always;\n"
    ));
    out.push_str(&format!("{indent}if ($request_method = OPTIONS) {{\n"));
    out.push_str(&format!("{indent}    return 204;\n"));
    out.push_str(&format!("{indent}}}\n"));
}

fn push_proxy_location(out: &mut String, proxy: &ProxyConfig, cors: bool) {
    let clean_prefix = proxy.prefix.trim_matches('/');
    if clean_prefix.is_empty() || proxy.target.trim().is_empty() {
        return;
    }

    let location = format!("/{}", clean_prefix);
    let target = nginx_proxy_target(&proxy.target);
    out.push('\n');
    push_nginx_line(out, 4, &format!("location = {location} {{"));
    push_nginx_line(out, 8, &format!("proxy_pass {target};"));
    push_nginx_line(out, 8, "proxy_http_version 1.1;");
    push_nginx_line(out, 8, "proxy_set_header Host $host;");
    push_nginx_line(out, 8, "proxy_set_header X-Real-IP $remote_addr;");
    push_nginx_line(out, 8, "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
    push_nginx_line(out, 8, "proxy_set_header X-Forwarded-Proto $scheme;");
    if cors {
        push_cors_headers(out, "        ");
    }
    push_nginx_line(out, 4, "}");

    out.push('\n');
    push_nginx_line(out, 4, &format!("location {location}/ {{"));
    push_nginx_line(out, 8, &format!("proxy_pass {target};"));
    push_nginx_line(out, 8, "proxy_http_version 1.1;");
    push_nginx_line(out, 8, "proxy_set_header Host $host;");
    push_nginx_line(out, 8, "proxy_set_header X-Real-IP $remote_addr;");
    push_nginx_line(out, 8, "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
    push_nginx_line(out, 8, "proxy_set_header X-Forwarded-Proto $scheme;");
    if cors {
        push_cors_headers(out, "        ");
    }
    push_nginx_line(out, 4, "}");
}

fn build_nginx_config(options: NginxConfigOptions) -> String {
    let service_name = options.service_name.trim();
    let listen_port = options.listen_port;
    let root_dir = escape_nginx_string(options.root_dir.trim());
    let url_prefix = options.url_prefix.as_deref().unwrap_or("/");
    let location = nginx_location_path(url_prefix);
    let index_page = options.index_page.as_deref().map(str::trim).filter(|s| !s.is_empty());
    let index_directive = match index_page {
        Some(page) => format!("{} index.html index.htm", page.trim_start_matches('/')),
        None => "index.html index.htm".to_string(),
    };
    let fallback = nginx_index_fallback(url_prefix, index_page);
    let cors = options.cors.unwrap_or(false);
    let gzip = options.gzip.unwrap_or(false);
    let access_log = options.access_log.unwrap_or(true);
    let error_log = options.error_log.unwrap_or(true);
    let proxies = options.proxies.unwrap_or_default();

    let mut out = String::new();
    push_nginx_line(&mut out, 0, "# Generated by Codeshelf Local Service");
    push_nginx_line(&mut out, 0, &format!("# Service: {service_name}"));
    out.push('\n');
    push_nginx_line(&mut out, 0, "server {");
    push_nginx_line(&mut out, 4, &format!("listen {listen_port};"));
    push_nginx_line(&mut out, 4, "server_name localhost 127.0.0.1;");
    push_nginx_line(&mut out, 4, "charset utf-8;");

    if gzip {
        out.push('\n');
        push_nginx_line(&mut out, 4, "gzip on;");
        push_nginx_line(&mut out, 4, "gzip_vary on;");
        push_nginx_line(&mut out, 4, "gzip_min_length 1024;");
        push_nginx_line(&mut out, 4, "gzip_types");
        push_nginx_line(&mut out, 8, "text/plain");
        push_nginx_line(&mut out, 8, "text/css");
        push_nginx_line(&mut out, 8, "application/json");
        push_nginx_line(&mut out, 8, "application/javascript");
        push_nginx_line(&mut out, 8, "text/xml");
        push_nginx_line(&mut out, 8, "application/xml");
        push_nginx_line(&mut out, 8, "application/xml+rss");
        push_nginx_line(&mut out, 8, "text/javascript");
        push_nginx_line(&mut out, 8, "image/svg+xml;");
    }

    if access_log {
        push_nginx_line(&mut out, 4, "access_log logs/codeshelf_access.log;");
    } else {
        push_nginx_line(&mut out, 4, "access_log off;");
    }
    if error_log {
        push_nginx_line(&mut out, 4, "error_log logs/codeshelf_error.log warn;");
    }

    for proxy in &proxies {
        push_proxy_location(&mut out, proxy, cors);
    }

    if location != "/" {
        let exact = location.trim_end_matches('/');
        out.push('\n');
        push_nginx_line(&mut out, 4, &format!("location = {exact} {{"));
        push_nginx_line(&mut out, 8, &format!("return 301 {location};"));
        push_nginx_line(&mut out, 4, "}");
        out.push('\n');
        push_nginx_line(&mut out, 4, &format!("location {location} {{"));
        push_nginx_line(&mut out, 8, &format!("alias \"{root_dir}/\";"));
        push_nginx_line(&mut out, 8, &format!("index {index_directive};"));
        push_nginx_line(&mut out, 8, &format!("try_files $uri $uri/ {fallback};"));
    } else {
        out.push('\n');
        push_nginx_line(&mut out, 4, &format!("root \"{root_dir}\";"));
        push_nginx_line(&mut out, 4, &format!("index {index_directive};"));
        out.push('\n');
        push_nginx_line(&mut out, 4, "location / {");
        push_nginx_line(&mut out, 8, &format!("try_files $uri $uri/ {fallback};"));
    }

    if cors {
        push_cors_headers(&mut out, "        ");
    }

    push_nginx_line(&mut out, 4, "}");
    push_nginx_line(&mut out, 0, "}");
    out
}

#[tauri::command]
#[specta::specta]
pub async fn generate_nginx_config(server_id: String) -> AppResult<String> {
    ensure_servers_loaded().await;

    let server = {
        let servers = SERVERS.lock().await;
        servers.get(&server_id).cloned()
    }
    .ok_or_else(|| crate::error::AppError::from(format!("服务不存在: {}", server_id)))?;

    Ok(build_nginx_config(NginxConfigOptions {
        service_name: server.name,
        listen_port: server.port,
        root_dir: server.root_dir,
        index_page: server.index_page,
        cors: Some(server.cors),
        gzip: Some(server.gzip),
        url_prefix: Some(server.url_prefix),
        proxies: Some(server.proxies),
        access_log: Some(true),
        error_log: Some(true),
    }))
}
